<a href="https://colab.research.google.com/github/janubro0125/Varsha-S-S-Machine-Learning/blob/main/KNN_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score

In [96]:
data=pd.read_csv("movies_dataset.csv")
data

        MovieID  ...           LeadActor
0             1  ...     Brian Mccormick
1             2  ...         Ashley Pena
2             3  ...     Alexander Haley
3             4  ...     Patrick Barnett
4             5  ...  Duane Fletcher DDS
...         ...  ...                 ...
999994   999995  ...     Stephanie Moore
999995   999996  ...         Tracy Klein
999996   999997  ...         Lynn Pierce
999997   999998  ...       Melissa Mcgee
999998   999999  ...    Samantha Sanders

[999999 rows x 17 columns]

In [97]:
data.dropna(inplace=True)

In [98]:
x=data[["ReleaseYear","IMDbRating","RottenTomatoesScore"]]
x

        ReleaseYear  IMDbRating  RottenTomatoesScore
0              2003         6.2                   58
1              1988         5.2                   44
2              1971         5.5                   55
3              1998         7.3                   87
4              2021         6.1                   67
...             ...         ...                  ...
999994         2011         4.8                   58
999995         1982         7.3                   83
999996         1993         4.1                   32
999997         2013         4.3                   23
999998         1995         6.6                   60

[999999 rows x 3 columns]

In [99]:
y=data["US_BoxOfficeUSD"]
y

0          6613685.82
1          1930949.15
2          4186694.69
3          2023683.92
4          2129629.10
             ...
999994     1075869.51
999995     1046949.86
999996    30619499.73
999997     3168114.87
999998    18626549.48
Name: US_BoxOfficeUSD, Length: 999999, dtype: float64

In [100]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=40)

In [101]:
model=KNeighborsRegressor(n_neighbors=5)
model.fit(x_train,y_train)

KNeighborsRegressor()

In [102]:
ReleaseYear=int(input("Enter the Release Year:"))
IMDbRating=float(input("Enter the IMDb Rating:"))
RottenTomatoesScore=int(input("Enter the Rotten Tomatoes Score:"))
inputss=[[ReleaseYear,IMDbRating,RottenTomatoesScore]]
print(model.predict(inputss))

Enter the Release Year:2020
Enter the IMDb Rating:4.5
Enter the Rotten Tomatoes Score:75
[6133495.972]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(